"""Build the app's data/*.js files from the spec-sheet JSON exports in tools/source/.
Run:  python3 tools/build_data.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'source')
OUT = os.path.join(HERE, '..', 'data')

gens = json.load(open(os.path.join(SRC, 'generators.json')))
eq = json.load(open(os.path.join(SRC, 'equipment.json')))
# Sizing-guide fuel ratings override the product-page scrape where they differ (see overrides.json _note).
_ov = json.load(open(os.path.join(SRC, 'overrides.json')))
for g in gens:
    g.update(_ov.get(g['model'], {}))

OUTLET_CAP = {'14-50R': 12000, 'L14-30R': 7200}   # 50A x 240V, 30A x 240V

def best_outlet(g):
    if (g.get('out_14_50r') or 0) > 0: return '14-50R'
    if (g.get('out_l14_30r') or 0) > 0: return 'L14-30R'
    return None

def fuel(g, p):
    s, r = g.get(p + '_starting_w'), g.get(p + '_running_w')
    if not r: return None
    d = {'starting': s or r, 'running': r}
    if p != 'ng':
        d['runtime25'] = g.get(p + '_runtime_25_hr')
        d['runtime50'] = g.get(p + '_runtime_50_hr')
    return d

import re
def dims(g):
    nums = [float(x) for x in re.findall(r'\d+(?:\.\d+)?', g.get('dimensions_in') or '')][:3]
    return nums if len(nums) == 3 else None

def family(g):
    m = g['model']
    if m == 'XP2300iH': return 'suitcase'
    if g['gen_type'] == 'Open frame inverter': return 'openInverter'
    if g['gen_type'] == 'Inverter': return 'inverterBlue' if m.startswith('XP7000') else 'inverter'
    return 'openFrame'

def colors(g):
    m = g['model']
    if g['brand'] == 'DuroStar':
        if m.startswith('DS10000'): return {'engine': '#d7261e', 'tank': '#d7261e', 'accent': '#d7261e'}
        return {'engine': '#d7261e', 'tank': '#1b1c1e', 'accent': '#d7261e'}
    if m in ('XP4850EH', 'XP11500EH'): return {'engine': '#2fae3b', 'tank': '#2fae3b', 'accent': '#2f7fd1'}
    return {'engine': '#1f56c9', 'tank': '#1f56c9', 'accent': '#1f56c9'}

out = []
for g in gens:
    bo = best_outlet(g)
    fuels = {}
    for p, name in (('gas', 'Gasoline'), ('lp', 'Propane'), ('ng', 'Natural Gas')):
        f = fuel(g, p)
        if f: fuels[name] = f
    out.append({
        'model': g['model'], 'brand': g['brand'], 'title': g['title'], 'type': g['gen_type'],
        'fuelConfig': g['fuel_config'], 'efi': bool(g.get('efi')), 'price': g.get('price_usd'),
        'salesStatus': g.get('sales_status'), 'fuels': fuels,
        'lpTankBasis': g.get('lp_runtime_tank'), 'tankGal': g.get('fuel_tank_gal'),
        'outlets': {k: g.get('out_' + k.lower().replace('-', '_')) or 0 for k in ('5-20R', 'L5-30R', 'TT-30R', 'L14-30R', '14-50R')},
        'bestOutlet': bo, 'outletCapW': OUTLET_CAP.get(bo, 0),
        'neutral': g.get('neutral_type'), 'unbondDoc': g.get('unbond_doc_url'), 'manual': g.get('manual_url'),
        'family': family(g), 'dimsIn': dims(g), 'colors': colors(g), 'noise': g.get('noise_db'), 'weightLb': g.get('weight_dry_lb') or g.get('weight_wet_lb'),
        'engineCc': g.get('engine_cc'), 'start': g.get('start_type'), 'coShutdown': g.get('co_shutdown'),
        'thd': g.get('thd'), 'warranty': g.get('warranty'), 'url': g.get('url'), 'image': g.get('image_url'),
    })

def keep(d, keys): return {k: d.get(k) for k in keys}
ts = [keep(t, ['sku', 'title', 'price_usd', 'available', 'location', 'amps', 'circuits', 'max_watts', 'circuit_breakers_included',
               'power_inlet_type_required', 'inlet_included', 'cord_included', 'wattmeters', 'url', 'image_url']) for t in eq['transfer_switches']]
ik = [keep(k, ['sku', 'title', 'price_usd', 'available', 'panel_brands', 'compatible_panel_models', 'main_breaker_amps',
               'breaker_orientation', 'url', 'image_url']) for k in eq['interlock_kits']]
ib = [keep(b, ['sku', 'title', 'price_usd', 'available', 'inlet_type', 'amps', 'max_watts', 'enclosure', 'url', 'image_url']) for b in eq['inlet_boxes']]
cords = [keep(c, ['sku', 'title', 'price_usd', 'available', 'plug_end', 'connector_end', 'amps', 'length_ft', 'gauge_awg', 'url', 'image_url'])
         for c in eq['cords'] if c['cord_type'] == 'Generator power cord' and c.get('plug_end')]
ss = [keep(a, ['sku', 'title', 'price_usd', 'available', 'product_category', 'url', 'image_url']) for a in eq['soft_starters']
      if 'EV' not in (a.get('product_category') or '')]

os.makedirs(OUT, exist_ok=True)
with open(os.path.join(OUT, 'generators.js'), 'w') as f:
    f.write('// Generated by tools/build_data.py from the DuroMax spec sheet. Do not edit by hand.\n')
    f.write('window.GENERATORS = ' + json.dumps(out, indent=1) + ';\n')
with open(os.path.join(OUT, 'equipment.js'), 'w') as f:
    f.write('// Generated by tools/build_data.py from the DuroMax spec sheet. Do not edit by hand.\n')
    f.write('window.EQUIPMENT = ' + json.dumps({'transferSwitches': ts, 'interlockKits': ik, 'inletBoxes': ib,
                                                'cords': cords, 'softStarters': ss, 'compatibility': eq['compatibility']}, indent=1) + ';\n')
print(len(out), 'generators;', len(ts), 'switches;', len(ik), 'interlocks;', len(ib), 'inlets;', len(cords), 'cords;', len(ss), 'soft starters')
